[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "app-manifest-cli"
version = "0.1.0"
description = "CLI"
authors = [{name = "Pavel Anikin"}]
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["typer>=0.12.3"]

[project.scripts]
app-manifest = "app_manifest_cli.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
