name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main
permissions:
  pull-requests: write
  contents: read
jobs:
  pr-auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: netcracker/qubership-workflow-hub/actions/pr-assigner@main
        with:
          assignees-count: 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
